// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVQYCpZE-5lIvFUO7dShkuLPLndk3iEbQ',
    appId: '1:283473083322:web:f4564b14fc5eb116213b83',
    messagingSenderId: '283473083322',
    projectId: 'bookverse-8a0eb',
    authDomain: 'bookverse-8a0eb.firebaseapp.com',
    storageBucket: 'bookverse-8a0eb.appspot.com',
    measurementId: 'G-1PL2XN1SEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiC3-bOTrTbJLjy_aT4LMJo8nHBeiKN4Q',
    appId: '1:283473083322:android:b7acb679346756ee213b83',
    messagingSenderId: '283473083322',
    projectId: 'bookverse-8a0eb',
    storageBucket: 'bookverse-8a0eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKFcI704f6oNCH1rbnKZwNUigoH3eFWWA',
    appId: '1:283473083322:ios:3338c3d7a2bc88a1213b83',
    messagingSenderId: '283473083322',
    projectId: 'bookverse-8a0eb',
    storageBucket: 'bookverse-8a0eb.appspot.com',
    iosBundleId: 'com.example.bookverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKFcI704f6oNCH1rbnKZwNUigoH3eFWWA',
    appId: '1:283473083322:ios:3338c3d7a2bc88a1213b83',
    messagingSenderId: '283473083322',
    projectId: 'bookverse-8a0eb',
    storageBucket: 'bookverse-8a0eb.appspot.com',
    iosBundleId: 'com.example.bookverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVQYCpZE-5lIvFUO7dShkuLPLndk3iEbQ',
    appId: '1:283473083322:web:7532492e2dfc199b213b83',
    messagingSenderId: '283473083322',
    projectId: 'bookverse-8a0eb',
    authDomain: 'bookverse-8a0eb.firebaseapp.com',
    storageBucket: 'bookverse-8a0eb.appspot.com',
    measurementId: 'G-YKP3KN5J67',
  );
}
